# Generated by Django 2.1 on 2018-08-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(help_text='ID', max_length=20)),
                ('first_name', models.CharField(help_text='first name', max_length=20)),
                ('last_name', models.CharField(help_text='last name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(help_text='ID', max_length=20)),
                ('first_name', models.CharField(help_text='first ame', max_length=20)),
                ('last_name', models.CharField(help_text='last name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(help_text='ID', max_length=20)),
                ('title', models.CharField(help_text='title', max_length=50)),
                ('updated', models.DateField(auto_now=True)),
                ('dek', models.CharField(help_text='summarize your post in one sentence', max_length=50)),
                ('text', models.TextField(help_text='text')),
                ('code', models.TextField(help_text='enter code or repl iframe')),
                ('pull_quotes', models.TextField(help_text='pull quote')),
                ('contributor', models.ManyToManyField(help_text='Select contributors', to='blog.Contributor')),
                ('editor', models.ManyToManyField(to='blog.Editor')),
            ],
        ),
    ]
